// Ethereum execution spec test generator.
// Reads JSON fixtures from execution-spec-tests and writes a Zig source file
// containing hardcoded test case data.

const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 3) {
        std.debug.print("Usage: spec-test-generator <fixtures-dir>... <output-file>\n", .{});
        std.process.exit(1);
    }

    const fixture_dirs = args[1 .. args.len - 1];
    const output_path = args[args.len - 1];

    // Collect all .json file paths from all fixture directories
    var json_paths: std.ArrayList([]const u8) = .empty;
    defer {
        for (json_paths.items) |p| allocator.free(p);
        json_paths.deinit(allocator);
    }
    for (fixture_dirs) |dir| {
        try collectJsonFiles(allocator, dir, &json_paths);
    }

    std.debug.print("Found {d} JSON fixture files\n", .{json_paths.items.len});

    // Open output file
    const out_file = try std.fs.cwd().createFile(output_path, .{});
    defer out_file.close();
    var buf: [4096]u8 = undefined;
    var file_writer = out_file.writerStreaming(&buf);
    const writer = &file_writer.interface;

    // Write header
    try writer.writeAll("// AUTO-GENERATED by spec-test-generator — do not edit\n");
    try writer.writeAll("const types = @import(\"types\");\n\n");
    try writer.writeAll("pub const test_cases: []const types.TestCase = &.{\n");

    var total_cases: usize = 0;
    var skipped: usize = 0;

    for (json_paths.items) |json_path| {
        const file_data = std.fs.cwd().readFileAlloc(allocator, json_path, 256 * 1024 * 1024) catch |err| {
            std.debug.print("Warning: Could not read {s}: {}\n", .{ json_path, err });
            continue;
        };
        defer allocator.free(file_data);

        const parsed = std.json.parseFromSlice(std.json.Value, allocator, file_data, .{}) catch |err| {
            std.debug.print("Warning: Could not parse {s}: {}\n", .{ json_path, err });
            continue;
        };
        defer parsed.deinit();

        const root = parsed.value;
        if (root != .object) continue;

        // Check if this file has any Osaka test entries
        var has_osaka = false;
        {
            var key_iter = root.object.iterator();
            while (key_iter.next()) |entry| {
                if (std.mem.indexOf(u8, entry.key_ptr.*, "fork_Osaka") != null) {
                    has_osaka = true;
                    break;
                }
            }
        }

        // Each top-level key is a test name
        var test_iter = root.object.iterator();
        while (test_iter.next()) |test_entry| {
            const test_name = test_entry.key_ptr.*;
            const test_obj = test_entry.value_ptr.*;
            if (test_obj != .object) continue;

            // Skip Prague entries when Osaka entries exist in the same file
            if (has_osaka and std.mem.indexOf(u8, test_name, "fork_Prague") != null) continue;

            const count = emitTestCases(allocator, writer, test_name, &test_obj.object) catch |err| {
                std.debug.print("Warning: Error processing test {s}: {}\n", .{ test_name, err });
                skipped += 1;
                continue;
            };
            total_cases += count;
        }
    }

    try writer.writeAll("};\n");
    try writer.flush();

    std.debug.print("Generated {d} test cases ({d} skipped)\n", .{ total_cases, skipped });
}

fn emitTestCases(allocator: std.mem.Allocator, writer: anytype, test_name: []const u8, obj: *const std.json.ObjectMap) !usize {
    const env = obj.get("env") orelse return 0;
    if (env != .object) return 0;
    const pre = obj.get("pre") orelse return 0;
    if (pre != .object) return 0;
    const transaction = obj.get("transaction") orelse return 0;
    if (transaction != .object) return 0;
    const post = obj.get("post") orelse return 0;
    if (post != .object) return 0;

    // Parse env
    const coinbase = try parseAddress(getStr(env.object, "currentCoinbase") orelse return 0);
    const block_number = try parseU256Hex(getStr(env.object, "currentNumber") orelse "0x0");
    const block_timestamp = try parseU256Hex(getStr(env.object, "currentTimestamp") orelse "0x0");
    const block_gaslimit = try parseU64Hex(getStr(env.object, "currentGasLimit") orelse "0x0");
    const block_basefee = try parseU64Hex(getStr(env.object, "currentBaseFee") orelse "0x0");
    const block_difficulty = try parseU256Hex(getStr(env.object, "currentDifficulty") orelse "0x0");
    const prevrandao = try parseU256Hex(getStr(env.object, "currentRandom") orelse getStr(env.object, "currentDifficulty") orelse "0x0");

    // Parse transaction fields
    const tx_sender = try parseAddress(getStr(transaction.object, "sender") orelse return 0);
    const tx_to_str = getStr(transaction.object, "to") orelse "";
    const is_create = tx_to_str.len == 0;
    const tx_to = if (is_create) [_]u8{0} ** 20 else try parseAddress(tx_to_str);
    const tx_gas_price = try parseU128Hex(getStr(transaction.object, "gasPrice") orelse "0x0");

    // Transaction arrays (data, gasLimit, value)
    const tx_data_arr = transaction.object.get("data") orelse return 0;
    if (tx_data_arr != .array) return 0;
    const tx_gas_arr = transaction.object.get("gasLimit") orelse return 0;
    if (tx_gas_arr != .array) return 0;
    const tx_value_arr = transaction.object.get("value") orelse return 0;
    if (tx_value_arr != .array) return 0;

    var count: usize = 0;

    // Prefer Osaka, fall back to Prague
    const fork_names = [_][]const u8{ "Osaka", "Prague" };
    var fork_name: []const u8 = undefined;
    var post_fork: std.json.Value = undefined;
    var found_fork = false;
    for (fork_names) |fn_| {
        if (post.object.get(fn_)) |pf| {
            if (pf == .array) {
                fork_name = fn_;
                post_fork = pf;
                found_fork = true;
                break;
            }
        }
    }
    if (!found_fork) return 0;

    for (post_fork.array.items) |post_entry| {
        if (post_entry != .object) continue;

        const indexes = post_entry.object.get("indexes") orelse continue;
        if (indexes != .object) continue;

        const data_idx = getUint(indexes.object, "data") orelse continue;
        const gas_idx = getUint(indexes.object, "gas") orelse continue;
        const value_idx = getUint(indexes.object, "value") orelse continue;

        if (data_idx >= tx_data_arr.array.items.len) continue;
        if (gas_idx >= tx_gas_arr.array.items.len) continue;
        if (value_idx >= tx_value_arr.array.items.len) continue;

        const calldata_hex = getJsonStr(tx_data_arr.array.items[data_idx]) orelse continue;
        const gas_limit_str = getJsonStr(tx_gas_arr.array.items[gas_idx]) orelse continue;
        const value_hex = getJsonStr(tx_value_arr.array.items[value_idx]) orelse continue;

        const gas_limit = try parseU64Hex(gas_limit_str);
        const value = try parseU256Hex(value_hex);

        // Check for expected exception
        const expect_exception = post_entry.object.get("expectException") != null;

        // Get expected state
        const expected_state = post_entry.object.get("state") orelse continue;
        if (expected_state != .object) continue;

        // Emit test case
        try writer.writeAll("    .{\n");

        // Name
        try writer.print("        .name = \"{s}_{s}_{d}_{d}_{d}\",\n", .{ test_name, fork_name, data_idx, gas_idx, value_idx });
        try writer.print("        .fork = \"{s}\",\n", .{fork_name});

        // Block env
        try emitAddrField(writer, "coinbase", coinbase);
        try emitU256Field(writer, "block_number", block_number);
        try emitU256Field(writer, "block_timestamp", block_timestamp);
        try writer.print("        .block_gaslimit = {d},\n", .{block_gaslimit});
        try writer.print("        .block_basefee = {d},\n", .{block_basefee});
        try emitU256Field(writer, "block_difficulty", block_difficulty);
        try emitU256Field(writer, "prevrandao", prevrandao);

        // Tx
        try emitAddrField(writer, "caller", tx_sender);
        try emitAddrField(writer, "target", tx_to);
        try writer.print("        .is_create = {s},\n", .{if (is_create) "true" else "false"});
        try emitU256Field(writer, "value", value);
        try emitBytesField(allocator, writer, "calldata", calldata_hex);
        try writer.print("        .gas_limit = {d},\n", .{gas_limit});
        try writer.print("        .gas_price = {d},\n", .{tx_gas_price});

        // Pre accounts
        try writer.writeAll("        .pre_accounts = &.{\n");
        var pre_iter = pre.object.iterator();
        while (pre_iter.next()) |pre_entry| {
            const addr_str = pre_entry.key_ptr.*;
            const acct = pre_entry.value_ptr.*;
            if (acct != .object) continue;

            const addr = try parseAddress(addr_str);
            const balance = try parseU256Hex(getStr(acct.object, "balance") orelse "0x0");
            const nonce = try parseU64Hex(getStr(acct.object, "nonce") orelse "0x0");
            const code_hex = getStr(acct.object, "code") orelse "0x";

            try writer.writeAll("            .{\n");
            try emitAddrField(writer, "address", addr);
            try emitU256Field(writer, "balance", balance);
            try writer.print("                .nonce = {d},\n", .{nonce});
            try emitBytesField(allocator, writer, "code", code_hex);

            // Storage
            const storage = acct.object.get("storage");
            if (storage != null and storage.? == .object) {
                try writer.writeAll("                .storage = &.{\n");
                var stor_iter = storage.?.object.iterator();
                while (stor_iter.next()) |stor_entry| {
                    const key_hex = stor_entry.key_ptr.*;
                    const val_str = getJsonStr(stor_entry.value_ptr.*) orelse continue;
                    const key = try parseU256Hex(key_hex);
                    const val = try parseU256Hex(val_str);
                    try writer.writeAll("                    .{ .key = ");
                    try emitU256Literal(writer, key);
                    try writer.writeAll(", .value = ");
                    try emitU256Literal(writer, val);
                    try writer.writeAll(" },\n");
                }
                try writer.writeAll("                },\n");
            } else {
                try writer.writeAll("                .storage = &.{},\n");
            }

            try writer.writeAll("            },\n");
        }
        try writer.writeAll("        },\n");

        // Expected storage
        try writer.writeAll("        .expected_storage = &.{\n");
        var exp_iter = expected_state.object.iterator();
        while (exp_iter.next()) |exp_entry| {
            const addr_str = exp_entry.key_ptr.*;
            const acct = exp_entry.value_ptr.*;
            if (acct != .object) continue;

            const addr = try parseAddress(addr_str);
            const storage = acct.object.get("storage");
            if (storage == null or storage.? != .object) continue;

            // Only emit accounts that have storage expectations
            const stor_obj = storage.?.object;
            if (stor_obj.count() == 0) continue;

            try writer.writeAll("            .{\n");
            try emitAddrField(writer, "address", addr);
            try writer.writeAll("                .storage = &.{\n");
            var stor_iter = stor_obj.iterator();
            while (stor_iter.next()) |stor_entry| {
                const key_hex = stor_entry.key_ptr.*;
                const val_str = getJsonStr(stor_entry.value_ptr.*) orelse continue;
                const key = try parseU256Hex(key_hex);
                const val = try parseU256Hex(val_str);
                try writer.writeAll("                    .{ .key = ");
                try emitU256Literal(writer, key);
                try writer.writeAll(", .value = ");
                try emitU256Literal(writer, val);
                try writer.writeAll(" },\n");
            }
            try writer.writeAll("                },\n");
            try writer.writeAll("            },\n");
        }
        try writer.writeAll("        },\n");

        try writer.print("        .expect_exception = {s},\n", .{if (expect_exception) "true" else "false"});
        try writer.writeAll("    },\n");
        count += 1;
    }

    return count;
}

// --- Emit helpers ---

fn emitAddrField(writer: anytype, name: []const u8, addr: [20]u8) !void {
    try writer.print("        .{s} = .{{ ", .{name});
    for (addr, 0..) |b, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("0x{x:0>2}", .{b});
    }
    try writer.writeAll(" },\n");
}

fn emitU256Field(writer: anytype, name: []const u8, val: [32]u8) !void {
    try writer.print("        .{s} = ", .{name});
    try emitU256Literal(writer, val);
    try writer.writeAll(",\n");
}

fn emitU256Literal(writer: anytype, val: [32]u8) !void {
    try writer.writeAll(".{ ");
    for (val, 0..) |b, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("0x{x:0>2}", .{b});
    }
    try writer.writeAll(" }");
}

fn emitBytesField(allocator: std.mem.Allocator, writer: anytype, name: []const u8, hex: []const u8) !void {
    const bytes = try hexToBytes(allocator, hex);
    defer allocator.free(bytes);

    try writer.print("        .{s} = &.{{ ", .{name});
    for (bytes, 0..) |b, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("0x{x:0>2}", .{b});
    }
    try writer.writeAll(" },\n");
}

// --- Parsing helpers ---

fn getStr(obj: std.json.ObjectMap, key: []const u8) ?[]const u8 {
    const val = obj.get(key) orelse return null;
    return getJsonStr(val);
}

fn getJsonStr(val: std.json.Value) ?[]const u8 {
    return switch (val) {
        .string => |s| s,
        else => null,
    };
}

fn getUint(obj: std.json.ObjectMap, key: []const u8) ?usize {
    const val = obj.get(key) orelse return null;
    return switch (val) {
        .integer => |i| @intCast(i),
        else => null,
    };
}

fn parseAddress(hex: []const u8) ![20]u8 {
    const stripped = stripPrefix(hex);
    var addr: [20]u8 = [_]u8{0} ** 20;
    if (stripped.len == 0) return addr;
    const start = if (stripped.len > 40) stripped.len - 40 else 0;
    const padded_len = stripped.len - start;
    const byte_len = (padded_len + 1) / 2;
    const offset = 20 - byte_len;
    var i: usize = 0;
    var si = start;
    if (padded_len % 2 == 1) {
        addr[offset] = try hexDigit(stripped[si]);
        si += 1;
        i = 1;
    }
    while (si + 1 < stripped.len) {
        addr[offset + i] = (try hexDigit(stripped[si])) << 4 | try hexDigit(stripped[si + 1]);
        si += 2;
        i += 1;
    }
    return addr;
}

fn parseU256Hex(hex: []const u8) ![32]u8 {
    const stripped = stripPrefix(hex);
    var result: [32]u8 = [_]u8{0} ** 32;
    if (stripped.len == 0) return result;
    const byte_len = (stripped.len + 1) / 2;
    if (byte_len > 32) return error.Overflow;
    const offset = 32 - byte_len;
    var i: usize = 0;
    var si: usize = 0;
    if (stripped.len % 2 == 1) {
        result[offset] = try hexDigit(stripped[0]);
        si = 1;
        i = 1;
    }
    while (si + 1 < stripped.len) {
        result[offset + i] = (try hexDigit(stripped[si])) << 4 | try hexDigit(stripped[si + 1]);
        si += 2;
        i += 1;
    }
    return result;
}

fn parseU64Hex(hex: []const u8) !u64 {
    const stripped = stripPrefix(hex);
    if (stripped.len == 0) return 0;
    var result: u64 = 0;
    for (stripped) |c| {
        result = std.math.mul(u64, result, 16) catch return error.Overflow;
        result = std.math.add(u64, result, try hexDigit(c)) catch return error.Overflow;
    }
    return result;
}

fn parseU128Hex(hex: []const u8) !u128 {
    const stripped = stripPrefix(hex);
    if (stripped.len == 0) return 0;
    var result: u128 = 0;
    for (stripped) |c| {
        result = std.math.mul(u128, result, 16) catch return error.Overflow;
        result = std.math.add(u128, result, try hexDigit(c)) catch return error.Overflow;
    }
    return result;
}

fn hexToBytes(allocator: std.mem.Allocator, hex: []const u8) ![]u8 {
    const stripped = stripPrefix(hex);
    if (stripped.len == 0) return allocator.alloc(u8, 0);

    const byte_len = (stripped.len + 1) / 2;
    const bytes = try allocator.alloc(u8, byte_len);
    errdefer allocator.free(bytes);

    var i: usize = 0;
    var si: usize = 0;
    if (stripped.len % 2 == 1) {
        bytes[0] = try hexDigit(stripped[0]);
        si = 1;
        i = 1;
    }
    while (si + 1 < stripped.len) {
        bytes[i] = (try hexDigit(stripped[si])) << 4 | try hexDigit(stripped[si + 1]);
        si += 2;
        i += 1;
    }
    return bytes;
}

fn stripPrefix(hex: []const u8) []const u8 {
    if (hex.len >= 2 and hex[0] == '0' and (hex[1] == 'x' or hex[1] == 'X')) {
        return hex[2..];
    }
    return hex;
}

fn hexDigit(c: u8) !u8 {
    return switch (c) {
        '0'...'9' => c - '0',
        'a'...'f' => c - 'a' + 10,
        'A'...'F' => c - 'A' + 10,
        else => error.InvalidHexChar,
    };
}

// --- File walking ---

fn collectJsonFiles(allocator: std.mem.Allocator, dir_path: []const u8, out: *std.ArrayList([]const u8)) !void {
    var dir = std.fs.cwd().openDir(dir_path, .{ .iterate = true }) catch |err| {
        std.debug.print("Warning: Could not open directory {s}: {}\n", .{ dir_path, err });
        return;
    };
    defer dir.close();

    var walker = try dir.walk(allocator);
    defer walker.deinit();

    while (try walker.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.basename, ".json")) continue;

        // Build full path
        const full_path = try std.fs.path.join(allocator, &.{ dir_path, entry.path });
        try out.append(allocator, full_path);
    }
}
